### ISSUE TITLE
Support Azure cli authentication

### ISSUE THREAD

**Issue by ahmad-hamade** [go-acme/lego#1458] opened 2021-07-27 14:58 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Library

### Detailed Description

I'm referring to this issue https://github.com/go-acme/lego/issues/1205 that has been opened for more than a year and I was wondering if there is any plan to support it?

We could use [hashicorp/go-azure-helpers](https://github.com/hashicorp/go-azure-helpers/tree/master/authentication) that covers all authentication scenarios that we use in Azure.

**Comment by ldez** [comment] 2021-07-27 15:00
Duplicate of #1205

**Closed by ldez** 2021-07-27 15:00 UTC
Labels: duplicate
