### ISSUE TITLE
DNS request prefer IPv6 only

### ISSUE THREAD

**Issue by ierdelyi** [go-acme/lego#2171] opened 2024-05-02 12:31 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

See this git issue: https://github.com/kchristensen/udm-le/issues/93
The lego use ipv6 dns server only.

### What did you see instead?

1; paramter to force ipv4 or ipv6
OR/AND
2 ; method to check all available dns servers
OR/AND
3; use DNS server whic was definied in command line

### How do you use lego?

Library

### Reproduction steps

Please see this isseues:
https://github.com/kchristensen/udm-le/issues/94
https://github.com/kchristensen/udm-le/issues/93

### Version of lego

```console
lego version 4.16.1 linux/arm64
```

### Logs

</details>2024/05/02 11:56:12 [INFO] [portal.owncompany.com] acme: Waiting for DNS record propagation.
2024/05/02 11:56:14 [INFO] [portal.owncompany.com] acme: Cleaning DNS-01 challenge
2024/05/02 11:56:16 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/345720099897
2024/05/02 11:56:16 Could not obtain certificates:
error: one or more domains had a problem:
[portal.owncompany.com] propagation: time limit exceeded: last error: DNS call error: read udp [2001:db8:1000::1]:51859->[2606:4700:50::adf5:3a38]:53: i/o timeout [ns=adi.ns.cloudflare.com.:53, question='_acme-challenge.portal.owncompany.com. IN TXT']
initial(): Starting udm-le systemd timer

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment] 2024-05-02 14:10
Duplicate of #1801

**Closed by ldez** 2024-05-02 14:10 UTC
Labels: duplicate
