### ISSUE TITLE
OVH DNS-01: "Error when call OVH api to add record : Error 404: This service does not exist"

### ISSUE THREAD

**Issue by PlqnK** [go-acme/lego#618] opened 2018-08-13 08:43 UTC
Hi!
I'm using Traefik (v1.6.5) and it's having issues renewing/creating Let's Encrypt certificates for my services just like described here on the Traefik repository: https://github.com/containous/traefik/issues/3415 where someone said that it's an issue with lego.
Here's what shows up in my logs:
```
Error when call OVH api to add record : "Error 404: \"This service does not exist\""                                                                                                
time="2018-08-13T07:56:16Z" level=error msg="Unable to obtain ACME certificate for domains \"subdomain.domain.tld\" detected thanks to rule \"Host:subdomain.domain.tld\" : cannot obtain certificates: acme: Error -> One or more domains had a problem:\n[subdomain.domain.tld] Error presenting token: Error 404: \"This service does not exist\"\n"
```
Here's the relevant part of my `docker-compose.yml`:
```yml
version: "2"
services:
  traefik:
    # https://hub.docker.com/_/traefik/
    image: traefik
    container_name: traefik
    restart: unless-stopped
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${LOCAL_STORAGE}/traefik/config/traefik.toml:/etc/traefik/traefik.toml
      - ${LOCAL_STORAGE}/traefik/config/acme.json:/acme.json
    environment:
      - OVH_ENDPOINT=${OVH_ENDPOINT}
      - OVH_APPLICATION_KEY=${OVH_APPLICATION_KEY}
      - OVH_APPLICATION_SECRET=${OVH_APPLICATION_SECRET}
      - OVH_CONSUMER_KEY=${OVH_CONSUMER_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.port=8080"
      - "traefik.frontend.rule=Host:traefik.${DOMAIN_NAME}"
```
The relevant part of my .env file:
```
## Global
LOCAL_STORAGE=/usr/local/share/docker-containers/data
DOMAIN_NAME=domain.tld

## Traefik
# See here to know which variables you need to set for your specific provider https://docs.traefik.io/configuration/acme/#provider
# For OVH first go to https://eu.api.ovh.com/createApp/ and create an API Application then type in a shell: curl -XPOST -H"X-Ovh-Application: YOURAPPKEY" -H "Content-type: application/json" https://eu.api.ovh.com/1.0/auth/credential  -d '{"accessRules":[{"method":"GET","path":"/*"},{"method":"POST","path":"/*"},{"method":"PUT","path":"/*"},{"method":"DELETE","path":"/*"}]}'
OVH_ENDPOINT=ovh-eu
OVH_APPLICATION_KEY=xxxxxxxxxxxxxxxx
OVH_APPLICATION_SECRET=yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
OVH_CONSUMER_KEY=zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
```
And my traefik.toml file:
```toml
debug = false
logLevel = "ERROR"

defaultEntryPoints = ["https","http"]
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
  [entryPoints.traefik]
  address = ":8080"
    [entryPoints.traefik.auth]
      [entryPoints.traefik.auth.basic]
      users = ["admin:$mypasswordhash"]

[api]
entryPoint = "traefik"
dashboard = true
debug = false

[retry]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "domain.tld"
watch = true
exposedbydefault = false

[acme]
email = "me@example.com"
storage = "acme.json"
entryPoint = "https"
OnHostRule = true
  [acme.dnsChallenge]
  # https://docs.traefik.io/configuration/acme/#provider
  provider = "OVH"
  delayBeforeCheck = 0
```
I want to point out that the certificate generation worked when I set up Traefik for the first time ~3 months ago and I deleted the ACME generated TXT records from my DNS zone since then (I don't know if it's relevant or not). I also tried to stop & delete the Traefik container, delete the acme.json file and recreate the Traefik container for it to try to generate the certificates like it was the first run but no luck, same error message in the logs.

Don't hesitate to ask if you want me to test something and thanks for taking the time to read me!

**Comment by PlqnK** [comment] 2018-08-13 09:11
I enabled debugging and changed the loglevel to debug in the traefik.toml file but there's no more information in the resulting logs about this error.

**Comment by AciDCooL** [comment] 2018-10-19 07:02
I'm having the same issue, contacted OVH what they changed but support did not respond with anything useful.

**Comment by ldubrois** [comment] 2018-12-12 14:56
Same problem. It used to be working, but now, getting the same error : 
```
error presenting token: ovh: error when call api to add record: Error 404: "This service does not exist"
```

**Comment by bbarou** [comment] 2018-12-17 10:14
I solved this using an external DNS Server.
Somehow it does not work when resolving using my DNS server.

As per the documention: https://docs.traefik.io/configuration/acme/

Just add a resolver in the acme section of the traefik.toml:
resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

**Comment by AciDCooL** [comment] 2018-12-17 10:56
Not working for me, but I was using google dns anyway since I have that in my router config. log after changing dns provider:

time="2018-12-17T10:50:54Z" level=info msg="Validating FQDN authority with DNS using [1.1.1.1:53 8.8.8.8:53]",
time="2018-12-17T10:50:54Z" level=info msg="legolog: [INFO] [*.XXXXXXX] acme: Obtaining bundled SAN certificate",
time="2018-12-17T10:50:55Z" level=info msg="legolog: [INFO] [*.XXXXXXX] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz/XXXXXXX",
time="2018-12-17T10:50:55Z" level=info msg="legolog: [INFO] [XXXXXXX] acme: Preparing to solve DNS-01",
time="2018-12-17T10:50:55Z" level=error msg="Unable to obtain ACME certificate for domains \"*.XXXXXX\" : unable to generate a certificate for the domains [*.XXXXXXX]: acme: Error -> One or more domains had a problem:\n[XXXXXXX] error presenting token: ovh: error when call api to add record: Error 404: \"This service does not exist\"\n",
time="2018-12-17T10:51:09Z" level=info msg="Skipping same configuration for provider docker",
time="2018-12-17T10:51:24Z" level=info msg="Skipping same configuration for provider docker",
time="2018-12-17T10:51:39Z" level=info msg="Skipping same configuration for provider docker",
time="2018-12-17T10:51:54Z" level=info msg="Skipping same configuration for provider docker",
time="2018-12-17T10:52:09Z" level=info msg="Skipping same configuration for provider docker",

**Comment by ldubrois** [comment] 2018-12-21 11:39
Appears to be a permission issue. The ovh application did no longer have permissions on the domains. The reported error message is wrong : it is not a 404 but more a 403/401 error.
My problem is solved.

**Comment by ldez** [comment] 2018-12-21 12:39
@ldubrois could you give the procedure that you're used to solving this?

**Comment by ldubrois** [comment] 2018-12-21 13:37
@ldez I've just recreated a new set of APIs key on https://eu.api.ovh.com/createToken/ 
Follow this guide for the permissions to grant : https://certbot-dns-ovh.readthedocs.io/en/stable/

I did not check all of it, but I think the account has expired or permissions set long time ago were not enough.

Error message provided by OVH was not the good one. Instead of Not Found, it should be Not authorized.

**Comment by ldez** [comment] 2018-12-31 08:01
could several other people confirm the solution of @ldubrois?

ping @AciDCooL

**Comment by AciDCooL** [comment] 2019-01-04 10:18
Ill try it this weekend, I moved the domain DNS to cloudflare for DNS-01 handling. I'll set the nameservers back and test on ovh.

**Comment by dauriata** [comment] 2021-08-20 17:16
> 
> 
> I tested it and I can't get it to work anymore, maybe because my dns isn't replicated fast enough after I change back the nameservers. I waited an entire day nothing. Ill stick to cloudflare in the meantime.
> 
> Maybe @Gibletron can test this on one of his domains.

I can confirm OVH DNS-01 works fine on my side

**Comment by dauriata** [comment] 2021-08-20 17:17
> 
> 
> could several other people confirm the solution of @ldubrois?
> 
> ping @AciDCooL

I can confirm OVH DNS-01 works fine on my side

**Closed** 2021-08-20 17:22 UTC
Labels: area/dnsprovider
