### ISSUE TITLE
Found CNAME entry for "_acme-challenge.xxx.com.": "mco.bbb.com."

### ISSUE THREAD

**Issue by tossp** [go-acme/lego#1800] opened 2023-01-06 03:28 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

Don't do cname verification

### What did you see instead?

```
Found CNAME entry for "_acme-challenge.xxx.com.": "mco.bbb.com."
```

### How do you use lego?

Binary

### Reproduction steps

1. Make an A record for the domain name( eg: xxx.com A 127.0.0.1)
2. Make another CName record of the universal domain name ( eg: *.xxx.com CNAME mco.bbb.com)

### Version of lego

```console
lego version 4.9.1 linux/amd64
```

### Logs

<details>

```console

+ ./lego --dns alidns --dns.resolvers 223.5.5.5 --pem -d xxx.com -d '*.xxx.com' -k=ec384 renew -days 7
2023/01/06 11:18:54 [INFO] [xxx.com] acme: Trying renewal with -3 hours remaining
2023/01/06 11:18:54 [INFO] [xxx.com, *.xxx.com] acme: Obtaining bundled SAN certificate
2023/01/06 11:18:56 [INFO] [*.xxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/******147
2023/01/06 11:18:56 [INFO] [xxx.com] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/******157
2023/01/06 11:18:56 [INFO] [*.xxx.com] acme: use dns-01 solver
2023/01/06 11:18:56 [INFO] [xxx.com] acme: Could not find solver for: tls-alpn-01
2023/01/06 11:18:56 [INFO] [xxx.com] acme: Could not find solver for: http-01
2023/01/06 11:18:56 [INFO] [xxx.com] acme: use dns-01 solver
2023/01/06 11:18:56 [INFO] [*.xxx.com] acme: Preparing to solve DNS-01
2023/01/06 11:18:56 [INFO] Found CNAME entry for "_acme-challenge.xxx.com.": "mco.bbb.com."
2023/01/06 11:18:56 [INFO] [xxx.com] acme: Preparing to solve DNS-01
2023/01/06 11:18:56 [INFO] Found CNAME entry for "_acme-challenge.xxx.com.": "mco.bbb.com."
2023/01/06 11:18:56 [INFO] [*.xxx.com] acme: Cleaning DNS-01 challenge
2023/01/06 11:18:56 [INFO] Found CNAME entry for "_acme-challenge.xxx.com.": "mco.bbb.com."
2023/01/06 11:18:57 [WARN] [*.xxx.com] acme: cleaning up failed: alicloud: zone bbb.com. not found in AliDNS for domain mco.bbb.com.
2023/01/06 11:18:57 [INFO] [xxx.com] acme: Cleaning DNS-01 challenge
2023/01/06 11:18:57 [INFO] Found CNAME entry for "_acme-challenge.xxx.com.": "mco.bbb.com."
2023/01/06 11:18:57 [WARN] [xxx.com] acme: cleaning up failed: alicloud: zone bbb.com. not found in AliDNS for domain mco.bbb.com.
2023/01/06 11:18:57 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/******147
2023/01/06 11:18:58 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/******157
2023/01/06 11:18:58 error: one or more domains had a problem:
[*.xxx.com] [*.xxx.com] acme: error presenting token: alicloud: zone bbb.com. not found in AliDNS for domain mco.bbb.com.
[xxx.com] [xxx.com] acme: error presenting token: alicloud: zone bbb.com. not found in AliDNS for domain mco.bbb.com.
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment] 2023-01-06 07:52
duplicate of https://github.com/go-acme/lego/issues/1754

**Closed by ldez** 2023-01-06 07:52 UTC
Labels: duplicate
