### ISSUE TITLE
Support for provider: 

### ISSUE THREAD

**Issue by zhishiguai** [go-acme/lego#1807] opened 2023-01-15 04:26 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Other

### Link to the DNS provider

HuaWeiCloud

### Link to the API documentation

https://support.huaweicloud.com/api-iam/iam_01_0006.html

### Additional Notes

ACME supports HUAWEI CLOUD, and it is hoped that LEGO can also support it
acme：https://github.com/acmesh-official/acme.sh/wiki/dnsapi2

**Comment by ldez** [comment] 2023-01-15 11:50
duplicate of #1543

**Closed by ldez** 2023-01-15 11:50 UTC
Labels: enhancement, new-provider
