### ISSUE TITLE
Error "unexpected authZone" on top-level domain with `gandiv5` provider

### ISSUE THREAD

**Issue by ambroisie** [go-acme/lego#1772] opened 2022-11-28 12:43 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

When running the following command:

```sh
export GANDIV5_API_KEY=<key>
lego --email <email> -d belanyi.fr -d '*.belanyi.fr' --dns gandiv5 run
```

I would expect the DNS challenge to work, both for the top-level as well as the wildcard.

### What did you see instead?

Instead I get an error for both the naked top-level domain as well as the wildcard.

<details>
<summary>Error log</summary>

```console
error: one or more domains had a problem:
[*.belanyi.fr] [*.belanyi.fr] acme: error presenting token: gandiv5: unexpected authZone belanyi.fr. for fqdn belanyi.fr.
[belanyi.fr] [belanyi.fr] acme: error presenting token: gandiv5: unexpected authZone belanyi.fr. for fqdn belanyi.fr.
```

</details>

### How do you use lego?

Binary

### Reproduction steps

1. `export GANDIV5_API_KEY=<key>`
2. `lego --email <email> -d <top-domain-or-top-domain-wildcard> --dns gandiv5 run`

### Version of lego

```console
lego version 4.9.0 linux/amd64
```

### Logs

<details>

```console
2022/11/28 13:41:45 [INFO] [belanyi.fr, *.belanyi.fr] acme: Obtaining bundled SAN certificate
2022/11/28 13:41:46 [INFO] [*.belanyi.fr] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/181490333787
2022/11/28 13:41:46 [INFO] [belanyi.fr] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/181490333797
2022/11/28 13:41:46 [INFO] [*.belanyi.fr] acme: use dns-01 solver
2022/11/28 13:41:46 [INFO] [belanyi.fr] acme: Could not find solver for: tls-alpn-01
2022/11/28 13:41:46 [INFO] [belanyi.fr] acme: Could not find solver for: http-01
2022/11/28 13:41:46 [INFO] [belanyi.fr] acme: use dns-01 solver
2022/11/28 13:41:46 [INFO] [*.belanyi.fr] acme: Preparing to solve DNS-01
2022/11/28 13:41:59 [INFO] [belanyi.fr] acme: Preparing to solve DNS-01
2022/11/28 13:42:11 [INFO] [*.belanyi.fr] acme: Cleaning DNS-01 challenge
2022/11/28 13:42:23 [INFO] [belanyi.fr] acme: Cleaning DNS-01 challenge
2022/11/28 13:42:35 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/181490333787
2022/11/28 13:42:35 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/181490333797
2022/11/28 13:42:35 Could not obtain certificates:
        error: one or more domains had a problem:
[*.belanyi.fr] [*.belanyi.fr] acme: error presenting token: gandiv5: unexpected authZone belanyi.fr. for fqdn belanyi.fr.
[belanyi.fr] [belanyi.fr] acme: error presenting token: gandiv5: unexpected authZone belanyi.fr. for fqdn belanyi.fr.
```

</details>

### Go environment (if applicable)

N/A

**Comment by mnordhoff** [comment] 2022-11-28 12:45
The same code is also in the `gandi` and `glesys1 providers.

**Comment by ambroisie** [comment] 2022-11-28 12:45
I found #403 with the same error message, but I am not doing a request that crosses zones.

However looking at [the verification code](https://github.com/go-acme/lego/blob/a7b11e0447290f8a8a6e1b38317fbf7e604ca890/providers/dns/gandiv5/gandiv5.go#L122-L125), it looks to me like it always checks if my FQDN ends in `.belanyi.fr.` but that disallows using the top domain itself.

This same logic can be found in `gandi`, `glesys`, and probably other providers.

So am I misunderstanding something here, or has this been a long standing bug?

**Comment by ldez** [comment] 2022-11-28 13:05
Hello,

can you try v4.9.1?

**Comment by ambroisie** [comment] 2022-11-28 13:20
@ldez same problem on v4.9.1.

**Comment by ambroisie** [comment] 2022-11-28 13:26
I have a CNAME wildcard like so:

```
* 10800 IN CNAME @
@ 10800 IN A <ip>
```

**Comment by ambroisie** [comment] 2022-11-28 13:27
FYI, v4.3.1 works flawlessly with this same command (I am currently building v4.8.0 to check a more recent example and reduce the bisection work).

**Comment by ldez** [comment] 2022-11-28 13:43
Since [v4.9.0](https://github.com/go-acme/lego/releases/tag/v4.9.0) lego follows CNAME as expected by the ACME, see https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname 

It's a kind of duplicate of #1754, #1756

So can you try to set the env var `LEGO_DISABLE_CNAME_SUPPORT` to `true`?

**Comment by ambroisie** [comment] 2022-11-28 13:51
That does work. However I expect it to be more of a hack than a long term solution, what would you recommend I do to fix it?

Sorry about the duplication, I did not realise.

**Comment by ldez** [comment] 2022-11-28 14:08
> what would you recommend I do to fix it?

I recommend creating a dedicated CNAME for the challenge if it's possible.

Related to the different feedback, I will keep `LEGO_DISABLE_CNAME_SUPPORT` so you can use it in production.

**Comment by ambroisie** [comment] 2022-11-28 14:17
> I recommend creating a dedicated CNAME for the challenge if it's possible.

As in the following?

```
_acme-challenge 10800 IN CNAME @
```

**Comment by Lefuneste83** [comment] 2023-01-29 00:01
Hi there
Yes this behavior is confirmed on my side.
Upgrading from docker image for Traefik 2.9.1 to 2.9.4 and subsequent (bringing lego 4.9.0+).
I am unable to process a cert renewal (wildcard gandiv5 dns challenge) with the following error : 

`time="2023-01-28T17:13:58+01:00" level=error msg="Error renewing certificate from LE: {subdomain.domain.name [*.subdomain.domain.name]}" providerName=letsencrypt.acme error="error: one or more domains had a problem:\n[*.subdomain.domain.name] [*.subdomain.domain.name] acme: error presenting token: gandiv5: unexpected authZone domain.name. for fqdn domain.name.\n[subdomain.domain.name] [subdomain.domain.name] acme: error presenting token: gandiv5: unexpected authZone domain.name. for fqdn domain.name.\n" ACME CA="https://acme-v02.api.letsencrypt.org/directory"`

Adding the following environment variable to the Traefik docker compose definition solves the issue : 

```
    environment:
      - LEGO_DISABLE_CNAME_SUPPORT=true
```

**Closed** 2023-01-29 11:01 UTC
Labels: question, area/dnsprovider, contrib/waiting-for-feedback
