### ISSUE TITLE
build fails with missing sacloud dependency

### ISSUE THREAD

**Issue by donpdonp** [go-acme/lego#1320] opened 2020-12-15 20:36 UTC
trying to build lego on freebsd with go 1.15.3 results in missing packages
```
$ go get -u github.com/go-acme/lego/cmd/lego
cannot find package "github.com/sacloud/libsacloud/api" in any of:
	/opt/go/1.15.3/src/github.com/sacloud/libsacloud/api (from $GOROOT)
	/home/donp/go/src/github.com/sacloud/libsacloud/api (from $GOPATH)
cannot find package "github.com/sacloud/libsacloud/sacloud" in any of:
	/opt/go/1.15.3/src/github.com/sacloud/libsacloud/sacloud (from $GOROOT)
	/home/donp/go/src/github.com/sacloud/libsacloud/sacloud (from $GOPATH)
```

**Comment by ldez** [comment] 2020-12-15 20:48
duplicate of  #993

**Closed by ldez** 2020-12-15 20:48 UTC

**Comment by donpdonp** [comment] 2020-12-15 20:54
Im not sure what this means. #993 talks about using lego/v3 - are you saying only lego versions 3.* are available to freebsd?

this seems more like the go.mod file should be using the sacloud branch 'v1' instead of master.

**Comment by ldez** [comment] 2020-12-15 21:10
https://go-acme.github.io/lego/installation/#from-sources

> To install the latest development version from sources, just run:
>
>      go get -u github.com/go-acme/lego/v4/cmd/lego
>

**Comment by ldez** [comment] 2020-12-15 21:14
It's not related to FreeBSD, it's related to the fact that you are trying to get a very old version of lego.

The v1 of lego doesn't use go modules, because go modules appear after the v1 of lego.

The current version of lego is v4.1.3

**Comment by ldez** [comment] 2020-12-15 21:22
The recommended ways to install and use lego are described in the documentation https://go-acme.github.io/lego/installation/:
- binaries
- docker image
- package managers


The easiest way for FreeBSD is:
- https://go-acme.github.io/lego/installation/#from-package-managers
- https://www.freshports.org/security/lego

**Comment by donpdonp** [comment] 2020-12-15 22:37
I tried the docs with the `lego/v4/cmd/lego` path

```
$ go get -u github.com/go-acme/lego/v4/cmd/lego
cannot find package "github.com/go-acme/lego/v4/cmd/lego" in any of:
	/opt/go/1.15.3/src/github.com/go-acme/lego/v4/cmd/lego (from $GOROOT)
	/home/donp/go/src/github.com/go-acme/lego/v4/cmd/lego (from $GOPATH)
```

which didnt make much sense to me as the folder for go-acme/lego/ does not have a /v3 or /v4 folder. is that part of the path some part of go module magic? the ticket was filed with `go get -u github.com/go-acme/lego/cmd/lego` which did appear to be building, but the go.mod seems to have a problem with the sacloud depedency path. 

I would prefer to build it myself as I have done in the past, but the go build system always seems to throw a wrench into the works. Ive tried the same commands with and without `GO111MODULE=on`

**Comment by donpdonp** [comment] 2020-12-15 22:55
it appears the `/v4` is the key to success, which threw me off because the repo has no folder v4 but I assume its part of go build module magic.

```
$ GO111MODULE=on go get -u github.com/go-acme/lego/v4/cmd/lego
$ ./go/bin/lego -v
lego version dev freebsd/amd64
```

thanks for the help!
