### ISSUE TITLE
dnspod provider compile failures in go1.12.5

### ISSUE THREAD

**Issue by hjweddie** [go-acme/lego#905] opened 2019-06-11 09:25 UTC
i encounter compile failures when i use dnspod's dns provider and go1.12.5, and error messages are as bellow

```
vendor/github.com/go-acme/lego/providers/dns/dnspod/dnspod.go:140:19: cannot convert 0 (type untyped number) to type "encoding/json".Number
vendor/github.com/go-acme/lego/providers/dns/dnspod/dnspod.go:140:19: invalid operation: hostedZone.ID == 0 (mismatched types "encoding/json".Number and int)
```

when i compile it with go1.12.4, it success with no errors

**Comment by ldez** [comment] 2019-06-11 10:51
duplicate of #876  #827

**Closed by ldez** 2019-06-11 10:51 UTC
Labels: duplicate
