### ISSUE TITLE
Allow setting wait time manually before DNS propagation is assumed complete

### ISSUE THREAD

**Issue by belidzs** [go-acme/lego#2253] opened 2024-08-29 10:00 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

I use lego to renew certificates in an environment where external DNS queries are blocked. This means it's not possible to query the authoritive DNS servers and using the local ones for this purpose is not a reliable method due to caching. Because of this, using `--dns.disable-cp` is not helping in this case (it returns propagated immediately if it already has something in the cache).

A solution would be if I could define a specific waiting time between creating the DNS record and asking the ACME server to validate it. With an appropriately set interval, the record is probably already propagated and the server will be able to validate it.

A similar approach has been implemented Traefik and it works quite well

**Comment by ldez** [comment] 2024-08-29 13:06
duplicate of #2030

**Closed by ldez** 2024-08-29 13:06 UTC
Labels: duplicate
