### ISSUE TITLE
Build failure: cannot convert 0 to type "encoding/json".Number w/ latest dnspod-go

### ISSUE THREAD

**Issue by eclipseo** [go-acme/lego#876] opened 2019-05-03 11:37 UTC
Golang 1.12.2 on Fedora Rawhide, dnspod-go master https://github.com/decker502/dnspod-go/commit/71fbbdbdf1a7eeac949586de15bf96d416d3dd63

```
# github.com/go-acme/lego/providers/dns/dnspod
../providers/dns/dnspod/dnspod.go:140:19: cannot convert 0 (type untyped number) to type "encoding/json".Number
../providers/dns/dnspod/dnspod.go:140:19: invalid operation: hostedZone.ID == 0 (mismatched types "encoding/json".Number and int)
FAIL	github.com/go-acme/lego/cmd [build failed]
```

Latest version of dnspod-go uses json.Number instead of int for its ID field. Base type of json.Number is string, see https://golang.org/pkg/encoding/json/#Number

**Comment by ldez** [comment] 2019-05-03 12:10
duplicate of #827

**Closed by ldez** 2019-05-03 12:10 UTC
