### ISSUE TITLE
Support for provider: Dynadot

### ISSUE THREAD

**Issue by NickPikachu** [go-acme/lego#2360] opened 2024-11-25 15:00 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Through 1Panel

### Link to the DNS provider

https://www.dynadot.com/

### Link to the API documentation

https://www.dynadot.com/domain/api

### Additional Notes

Dynadot provides a method that allows you to modify the DNS of a specific domain name, and has comprehensive API usage documentation. I would be happy to help if I can. Thank you!

**Comment by ldez** [comment] 2024-11-25 15:01
Duplicate of #1397

**Closed by ldez** 2024-11-25 15:01 UTC
Labels: enhancement, new-provider
