### ISSUE TITLE
Build fail with dns/dnspod imported.

### ISSUE THREAD

**Issue by forewing** [go-acme/lego#907] opened 2019-06-14 11:12 UTC
## 1. Version.

Docker image:
```
golang:1.12.4-alpine
```

Lego: 
```
acme/lego@v2.5.0
```

## 2. What are you trying to do?

Build Caddy with dnspod plugin. 

Build script: [builder.sh](https://github.com/abiosoft/caddy-docker/blob/master/builder/builder.sh)

Command: `$PLUGINS="dnspod" /bin/sh builder.sh`

## 3. Error Message.

```
# github.com/go-acme/lego/providers/dns/dnspod
/go/pkg/mod/github.com/go-acme/lego@v2.5.0+incompatible/providers/dns/dnspod/dnspod.go:140:19: cannot convert 0 (type untyped number) to type "encoding/json".Number
/go/pkg/mod/github.com/go-acme/lego@v2.5.0+incompatible/providers/dns/dnspod/dnspod.go:140:19: invalid operation: hostedZone.ID == 0 (mismatched types "encoding/json".Number and int)
error at 'building caddy'
```

**Comment by ldez** [comment] 2019-06-14 12:22
duplicate of #905,#876 #827

**Closed by ldez** 2019-06-14 12:22 UTC
Labels: duplicate
