### ISSUE TITLE
IONOS DNS Cleanup does not work

### ISSUE THREAD

**Issue by jackc94** [go-acme/lego#2096] opened 2024-01-30 17:58 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

2024/01/30 17:39:10 [INFO] [example2.mydomain.co.uk] acme: Cleaning DNS-01 challenge to clear the TXT record created for validation.

### What did you see instead?

The TXT record remained in my IONOS DNS list:
_acme-challenge.example2.mydomain.co.uk 300 IN TXT "<VALUE>"

### How do you use lego?

Library

### Reproduction steps

1. Start a new request using: IONOS_API_KEY=<API_PUBLIC_PREFIX.API_SECRET> lego --email admin@mydomain.co.uk --dns ionos --domains example2.mydomain.co.uk run
2. New TXT record created for the challenge: _acme-challenge.example2.mydomain.co.uk 300 IN TXT "<VALUE>"
3. Run through validation then the cleanup process clean DNS-01 challenge removing the TXT record from IONOS.
4. Despite reporting this step has completed the TXT record remains. 

### Version of lego

```console
lego version dev linux/arm64
```

### Logs

<details>

```console
2024/01/30 17:38:59 [INFO] [example2.mydomain.co.uk] acme: Obtaining bundled SAN certificate
2024/01/30 17:39:00 [INFO] [example2.mydomain.co.uk] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/309789279237
2024/01/30 17:39:00 [INFO] [example2.mydomain.co.uk] acme: Could not find solver for: tls-alpn-01
2024/01/30 17:39:00 [INFO] [example2.mydomain.co.uk] acme: Could not find solver for: http-01
2024/01/30 17:39:00 [INFO] [example2.mydomain.co.uk] acme: use dns-01 solver
2024/01/30 17:39:00 [INFO] [example2.mydomain.co.uk] acme: Preparing to solve DNS-01
2024/01/30 17:39:02 [INFO] [example2.mydomain.co.uk] acme: Trying to solve DNS-01
2024/01/30 17:39:02 [INFO] [example2.mydomain.co.uk] acme: Checking DNS record propagation using [10.3.165.1:53]
2024/01/30 17:39:04 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2024/01/30 17:39:10 [INFO] [example2.mydomain.co.uk] The server validated our request
2024/01/30 17:39:10 [INFO] [example2.mydomain.co.uk] acme: Cleaning DNS-01 challenge
2024/01/30 17:39:13 [INFO] [example2.mydomain.co.uk] acme: Validations succeeded; requesting certificates
2024/01/30 17:39:15 [INFO] [example2.mydomain.co.uk] Server responded with a certificate.
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment] 2024-01-30 18:15
duplicate of #2082

**Closed by ldez** 2024-01-30 18:15 UTC
Labels: duplicate
