### ISSUE TITLE
System configuration document for Lego

### ISSUE THREAD

**Issue by suvsap** [go-acme/lego#1132] opened 2020-05-01 16:33 UTC
Thanks Idez for your quick update.

So as per my understanding there is no dependency on Ubuntu version. Lego v3.5.0 can run on any Ubuntu version.

Also can you kindly point to some documentation for the same so that I can update it in my ticket before proceeding with the upgrade.

Best Regards,
Suvankar

_Originally posted by @suvsap in https://github.com/go-acme/lego/issues/1131#issuecomment-622452544_

**Comment by ldez** [comment] 2020-05-01 16:43
duplicate of #1131

**Closed by ldez** 2020-05-01 16:43 UTC
