### ISSUE TITLE
Constellix DNS-01 challenge not working

### ISSUE THREAD

**Issue by dsantanu** [go-acme/lego#1188] opened 2020-06-14 10:29 UTC
Can anyone confirm if this actually works with Constellix? With DNS-01 and it's actually adding the TXT record nicely but fails to get the cert with the error below:
```
2020/06/13 09:03:39 [INFO] [dsm15.xxxx.net] acme: Cleaning DNS-01 challenge
2020/06/13 09:03:42 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/ac ... 5208690466
2020/06/13 09:03:42 Could not obtain certificates:
error: one or more domains had a problem:
[dsm15.xxxx.net] time limit exceeded: last error: NS ns21.constellix.com. returned REFUSED for _acme-challenge.dsm15.xxxx.net.
```

Even though it's saying that *Cleaning DNS-01 challenge*, it actually doesn't but that's probably because of the error just after that. I'm getting the very same error for every single host I try. The same domains works absolutely fine using **acme.sh** though.

Any idea what I might be missing? This is the command I'm using:
```
CONSTELLIX_API_KEY_FILE=Constellix_Api CONSTELLIX_SECRET_KEY_FILE=Constellix_Secret \
lego -a --dns constellix -d 'dsm15.xxxx.net' -m admin@xxxx.co.uk --path '/share/CACHEDEV1_DATA/.qpkg/LEgo/.lego/' run
```
Any help/pointer would be greatly appreciated!!

**Comment by ldez** [comment] 2020-06-14 11:21
Hello,

> Can anyone confirm if this actually works with Constellix?

I can confirm it works. (I created the provider and I have a Constellix account)

> NS ns21.constellix.com. returned REFUSED for _acme-challenge.dsm15.xxxx.net.

It's a DNS response, `REFUSED` means "The name server refuses to perform the specified operation for policy reasons"

**Comment by dsantanu** [comment] 2020-06-14 16:52
Hi @ldez , thanks for bringing us that provider. Absolutely nice job regardless of it's working for me or not. 
 
Okay, now I'm a bit confused here: First of all, `Constellix_Api` and `Constellix_Secret` are the name of the two files, which holds only the API and the Secret keys respectively. And I think `\` doesn't actually matter, if you put that in the same line - isn't it? I put `CONSTELLIX_API_KEY_FILE` and `CONSTELLIX_SECRET_KEY_FILE` in the same line and created a new line for the actual command for readability. I don't think it could actually add the TXT record (without the a proper pair of Api and the Secret key) If there were any issue there. 

The stand alone `dig` command does work and as I said, I can create the the cert without any issue if I use **acme.sh** directly. 
```
; <<>> DiG 9.10.1-P2 <<>> @ns21.constellix.com _acme-challenge.dsm15.xxxx.net. TXT
; (1 server found)
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 7576
;; flags: qr rd ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1432
;; QUESTION SECTION:
;_acme-challenge.dsm15.xxxx.net.	IN TXT

;; AUTHORITY SECTION:
xxxx.net.	43	IN	SOA	ns11.constellix.com. dns.constellix.com. 2015010148 43200 3600 1209600 180

;; Query time: 0 msec
;; SERVER: 46.31.236.1#53(46.31.236.1)
;; WHEN: Sun Jun 14 17:26:23 BST 2020
;; MSG SIZE  rcvd: 126
```
How do I generate the log? Do you mean the *stdout* running the command?

**Comment by dsantanu** [comment] 2020-06-14 17:03
Anyway, below is the output from console (if that's what you mean): 
```
[/share/CACHEDEV1_DATA/.qpkg/LEgo/.lego] # CONSTELLIX_API_KEY_FILE=Constellix_Api CONSTELLIX_SECRET_KEY_FILE=Constellix_Secret lego -a --dns constellix -d 'dsm15.xxxx.net' -m admin@xxxx.co.uk --path '/share/CACHEDEV1_DATA/.qpkg/LEgo/.lego/' run
2020/06/14 17:54:38 [INFO] [dsm15.xxxx.net] acme: Obtaining bundled SAN certificate
2020/06/14 17:54:39 [INFO] [dsm15.xxxx.net] AuthURL: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5236895468
2020/06/14 17:54:39 [INFO] [dsm15.xxxx.net] acme: Could not find solver for: tls-alpn-01
2020/06/14 17:54:39 [INFO] [dsm15.xxxx.net] acme: Could not find solver for: http-01
2020/06/14 17:54:39 [INFO] [dsm15.xxxx.net] acme: use dns-01 solver
2020/06/14 17:54:39 [INFO] [dsm15.xxxx.net] acme: Preparing to solve DNS-01
2020/06/14 17:54:45 [INFO] [dsm15.xxxx.net] acme: Trying to solve DNS-01
2020/06/14 17:54:45 [INFO] [dsm15.xxxx.net] acme: Checking DNS record propagation using [127.0.1.1:53]
2020/06/14 17:54:45 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/06/14 17:54:45 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:54:47 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:54:49 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:54:51 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:54:53 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:54:55 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:54:57 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:54:59 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:01 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:03 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:05 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:07 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:09 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:11 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:13 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:15 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:17 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:19 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:21 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:23 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:25 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:27 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:29 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:31 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:33 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:35 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:37 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:39 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:41 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:43 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 17:55:45 [INFO] [dsm15.xxxx.net] acme: Cleaning DNS-01 challenge
2020/06/14 17:55:48 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5236895468
2020/06/14 17:55:48 Could not obtain certificates:
    error: one or more domains had a problem:
[dsm15.xxxx.net] time limit exceeded: last error: NS ns31.constellix.com. returned REFUSED for _acme-challenge.dsm15.xxxx.net.
```
One thing: I'm running it on QNAP, if that makes it any different.

**Comment by ldez** [comment] 2020-06-14 18:43
From your logs:
```
2020/06/14 17:54:45 [INFO] [dsm15.xxxx.net] acme: Checking DNS record propagation using [127.0.1.1:53]
```

Your DNS resolver is `127.0.1.1:53` and I think it's the issue.

So you have 2 possibilities:
- add a nameserver in `/etc/resolv.conf`
- add a nameserver `--dns.resolvers` (ex: `--dns.resolvers 1.1.1.1`)

**Comment by dsantanu** [comment] 2020-06-14 20:21
nope, still no joy! and i'd be surprised if that was the case, as it works perfectly okay for the rest of the thngs, e.g. 
```
[/share/CACHEDEV1_DATA/.qpkg/LEgo/.lego] # host google.com
google.com has address 216.58.210.238
google.com has IPv6 address 2a00:1450:4009:81b::200e
google.com mail is handled by 20 alt1.aspmx.l.google.com.
google.com mail is handled by 10 aspmx.l.google.com.
google.com mail is handled by 30 alt2.aspmx.l.google.com.
google.com mail is handled by 40 alt3.aspmx.l.google.com.
google.com mail is handled by 50 alt4.aspmx.l.google.com.
``` 
but anyway, I did try `--dns.resolvers` and still the very same error:
```
......
2020/06/14 20:44:02 [INFO] [dsm15.xxxx.net] acme: Trying to solve DNS-01
2020/06/14 20:44:02 [INFO] [dsm15.xxxx.net] acme: Checking DNS record propagation using [1.1.1.1:53]
2020/06/14 20:44:02 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/06/14 20:44:02 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 20:44:04 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
.......
.......
2020/06/14 20:44:58 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 20:45:00 [INFO] [dsm15.xxxx.net] acme: Waiting for DNS record propagation.
2020/06/14 20:45:02 [INFO] [dsm15.xxxx.net] acme: Cleaning DNS-01 challenge
2020/06/14 20:45:07 [INFO] Deactivating auth: https://acme-v02.api.letsencrypt.org/acme/authz-v3/5239257334
2020/06/14 20:45:07 Could not obtain certificates:
    error: one or more domains had a problem:
[dsm15.xxxx.net] time limit exceeded: last error: NS ns31.constellix.com. returned REFUSED for _acme-challenge.dsm15.xxxx.net.
```
It seems something else that we are missing. What else can I try? Is there any _debug_ log or something?

-S

**Comment by ldez** [comment] 2020-06-14 20:42
The `REFUSED` error comes from the DNS (it's a DNS call, not an API call), so there are no more logs.

The problem is related to the communication with the DNS (not the DNS API), you have to:
- check the DNS communication `dig dsm15.xxxx.net A`
- check your DNS records

From my memory, `acme.sh` doesn't check the propagation.

The propagation check is important, because it avoid a lot of problem, but you can disable it:  `--dns.disable-cp`.
I don't recommend to disable the propagation check, I recommend to fix the communication with the DNS, but there is a workaround.

**Comment by dsantanu** [comment] 2020-06-14 22:30
hummm............. I'm not really sure if we are looking into right thing. The DNS part should be just fine, otherwise I wouldn't reach the site in the first place. But here is the `dig` test:

```
[~] # dig dsm15.xxxx.net A

; <<>> DiG 9.10.1-P2 <<>> dsm15.xxxx.net A
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 37295
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 4096
;; QUESTION SECTION:
;dsm15.xxxx.net.        IN    A

;; ANSWER SECTION:
dsm15.xxxx.net.    116    IN    A    116.xxx.xxx.9

;; Query time: 0 msec
;; SERVER: 127.0.1.1#53(127.0.1.1)
;; WHEN: Sun Jun 14 23:18:34 BST 2020
;; MSG SIZE  rcvd: 67
```

Now, with `--dns.disable-cp`, the error msg is changed:
```
2020/06/14 23:14:26 Could not obtain certificates:
    error: one or more domains had a problem:
[dsm15.xxxx.net] acme: error: 400 :: urn:ietf:params:acme:error:dns :: DNS problem: NXDOMAIN looking up TXT for _acme-challenge.dsm15.xxxx.net - check that a DNS record exists for this domain, url:
```
If you see here, the TXT record it's looking for is: `_acme-challenge.dsm15.xxxx.net` but according to the Constellix console, the added record is: **_acme-challenge.dsm15** only (i.e. without the domain part)
<img width="1207" alt="image" src="https://user-images.githubusercontent.com/4650237/84605641-cdd77b80-ae96-11ea-9a1c-02b8a7e0a206.png">

So, does it matter or it's a bug??

-S

**Comment by ldez** [comment] 2020-06-15 00:23
> DNS problem: NXDOMAIN looking up TXT for _acme-challenge.dsm15.xxxx.net

It's an expected error when you are using `--dns.disable-cp`

The TXT record seems good, but I still think that is a DNS communication error.

---

As you can see, it works for me:

```console
$ CONSTELLIX_API_KEY=xxxxxxxxxxx \
 CONSTELLIX_SECRET_KEY=yyyyyyyyyyyyyyyyy \
 ./lego -a \
 --server=https://acme-staging-v02.api.letsencrypt.org/directory \
 --dns constellix \
 --domains test.example.com \
 --email ldez@example.com run

2020/06/15 02:18:59 No key found for account ldez@example.com. Generating a P384 key.
2020/06/15 02:18:59 Saved key to ./.lego/accounts/acme-staging-v02.api.letsencrypt.org/ldez@example.com/keys/ldez@example.com.key
2020/06/15 02:19:00 [INFO] acme: Registering account for ldez@example.com
!!!! HEADS UP !!!!

Your account credentials have been saved in your Let's Encrypt
configuration directory at "./.lego/accounts".

You should make a secure backup of this folder now. This
configuration directory will also contain certificates and
private keys obtained from Let's Encrypt so making regular
backups of this folder is ideal.
2020/06/15 02:19:00 [INFO] [test.example.com] acme: Obtaining bundled SAN certificate
2020/06/15 02:19:01 [INFO] [test.example.com] AuthURL: https://acme-staging-v02.api.letsencrypt.org/acme/authz-v3/65488648
2020/06/15 02:19:01 [INFO] [test.example.com] acme: Could not find solver for: tls-alpn-01
2020/06/15 02:19:01 [INFO] [test.example.com] acme: Could not find solver for: http-01
2020/06/15 02:19:01 [INFO] [test.example.com] acme: use dns-01 solver
2020/06/15 02:19:01 [INFO] [test.example.com] acme: Preparing to solve DNS-01
2020/06/15 02:19:07 [INFO] [test.example.com] acme: Trying to solve DNS-01
2020/06/15 02:19:07 [INFO] [test.example.com] acme: Checking DNS record propagation using [192.168.1.1:53]
2020/06/15 02:19:07 [INFO] Wait for propagation [timeout: 1m0s, interval: 2s]
2020/06/15 02:19:07 [INFO] [test.example.com] acme: Waiting for DNS record propagation.
2020/06/15 02:19:09 [INFO] [test.example.com] acme: Waiting for DNS record propagation.
2020/06/15 02:19:12 [INFO] [test.example.com] acme: Waiting for DNS record propagation.
2020/06/15 02:19:20 [INFO] [test.example.com] The server validated our request
2020/06/15 02:19:20 [INFO] [test.example.com] acme: Cleaning DNS-01 challenge
2020/06/15 02:19:28 [INFO] [test.example.com] acme: Validations succeeded; requesting certificates
2020/06/15 02:19:29 [INFO] [test.example.com] Server responded with a certificate.
```

**Comment by dsantanu** [comment] 2020-06-15 07:40
> The TXT record seems good, but I still think that is a DNS communication error.

Any idea how do we test that or find out what exactly that _communication error_ might be? I'm running out of ideas: Tried whatever I possibly can but every other things seem to indicate a healthy DNS record, apart from this script. I can raise an case with constellix.com but I'm pretty sure they will end up with asking the same question as me: How it works for rest of everything? 

You sure the script is not doing anything not ordinary? any idea what might be the next step(s)?

-S

**Comment by dsantanu** [comment] 2020-07-01 06:49
hi! 
Just wanted to ask if there is anything else I can try? Or should I actually give up? 

-S

**Comment by ldez** [comment] 2020-07-01 07:24
I made some improvements, you can try the current master branch.

**Comment by dsantanu** [comment] 2020-07-01 16:36
sure! will give it a try tonight! ty!

**Comment by ldez** [comment] 2020-08-09 14:37
any news?

**Comment by ldez** [comment] 2020-08-26 19:25
As I have not had any feedback, I will therefore close this issue.

**Closed by ldez** 2020-08-26 19:25 UTC
Labels: contrib/waiting-for-feedback, question
