### ISSUE TITLE
DNS challenge CNAME resolution is incompatible with some wildcard CNAME configurations

### ISSUE THREAD

**Issue by lann** [go-acme/lego#1816] opened 2023-01-23 14:49 UTC
### Welcome

- [X] Yes, I'm using a binary release within 2 latest releases.
- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, I've included all information below (version, config, etc).

### What did you expect to see?

[`getChallengeFqdn`](https://github.com/go-acme/lego/blob/5ff9695c09086cb3497906f90fe65af0ef85b128/challenge/dns01/dns_challenge.go#L185) resolves CNAME records in order to support Let's Encrypt's suggestions for hosting providers: <https://letsencrypt.org/2019/10/09/onboarding-your-customers-with-lets-encrypt-and-acme.html#the-advantages-of-a-cname>

The implementation first constructs the "normal" DNS challenge domain (e.g. `_acme-challenge.example.com.`) and then recursively follows any CNAME records that match this domain to find the "true" challenge domain. This can causes problems if a wildcard cert is being requested for a domain with a wildcard CNAME record, e.g.: 

`*.example.com.  CNAME  load-balancer.third-party-cloud.com.`

In this case, `getChallengeFqdn` would resolve `_acme-challenge.example.com` to `load-balancer.third-party-cloud.com.`, but `third-party-cloud.com.` is not under the control of `example.com.`'s owner, so they cannot place the challenge TXT record in that zone.

This may be the root cause of #1754.

I'm not sure what the technical behavior should be here. I believe (but have not yet tested) that the issue can be worked around with an explicit CNAME, e.g. `_acme-challenge.com.  CNAME  _acme-challenge.sub.example.com.`, but the issue is currently very difficult to debug.

### What did you see instead?

From the example above, the equivalent error I have seen:

```
cloudflare: failed to find zone load-balancer.third-party-cloud.com.: zone could not be found
```

### How do you use lego?

Through Traefik

### Reproduction steps

1. Configure a wildcard CNAME pointing at a third-party load balancer
2. Attempt to request a cert using the dns provider hosting your CNAME wildcard

### Version of lego

```console
v4.9.1 (via Traefik v2.9.6)
```

### Logs

<details>

```console
cloudflare: failed to find zone load-balancer.third-party-cloud.com.: zone could not be found
```

</details>

### Go environment (if applicable)

<details>

```console
$ go version && go env
# paste output here
```

</details>

**Comment by ldez** [comment] 2023-01-23 15:41
Duplicate of #1792, #1754

You have to set the env var `LEGO_DISABLE_CNAME_SUPPORT` to `true`.

**Closed** 2023-01-23 15:42 UTC
Labels: bug

**Comment by lann** [comment] 2023-01-23 15:51
To clarify, do you

> consider this option as a part of the lego "contract"
https://github.com/go-acme/lego/issues/1754#issuecomment-1322409745

?

**Comment by ldez** [comment] 2023-01-23 16:35
This means the option can be used in production, we will not remove this option in a minor release.
