### ISSUE TITLE
Interest in moving DNS providers into a separate library?

### ISSUE THREAD

**Issue by anderspitman** [go-acme/lego#1251] opened 2020-09-18 19:04 UTC
Related ideas have been discussed in #111 and #1100.

Basically I think a generic library with a uniform interface for reading and modifying DNS records across multiple providers would be very useful. If it were developed in a separate library, it could be used by other projects. lego would become a consumer of that library and the burden of implementing new DNS providers would be completely removed from lego directly (you seem to get a lot of requests for new providers).

I haven't dug too deeply into the lego code yet. The main question is whether the current interface for providers is comprehensive enough to support general DNS record manipulation. For example if you're hard-coded for only changing TXT records, it might not be worth the effort to add the functionality and maybe it makes more sense for lego to keep a small, focused implementation.

Anyway, just wanted to float the idea and see if there was any interest in collaborating on such a thing.

**Comment by ldez** [comment] 2020-09-18 19:12
Duplicate of #992

**Closed by ldez** 2020-09-18 19:12 UTC

**Comment by anderspitman** [comment] 2020-09-22 22:24
[libdns](https://github.com/libdns/libdns) looks like what I want.
