### ISSUE TITLE
Support for provider: huaweicloud

### ISSUE THREAD

**Issue by PAKingdom** [go-acme/lego#1675] opened 2022-07-14 15:49 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [ ] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [ ] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Binary

### Link to the DNS provider

https://www.huaweicloud.com/intl/en-us/product/dns.html

### Link to the API documentation

https://support.huaweicloud.com/intl/en-us/api-dns/en-us_topic_0037134405.html

### Additional Notes

https://github.com/acmesh-official/acme.sh/wiki/dnsapi#123-use-huaweicloud-api

**Comment by ldez** [comment] 2022-07-14 16:52
duplicate of #1543

**Closed by ldez** 2022-07-14 16:52 UTC
Labels: duplicate
