### ISSUE TITLE
Support for provider: UKFast's SafeDNS

### ISSUE THREAD

**Issue by Xiol** [go-acme/lego#1544] opened 2021-12-16 14:51 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.
- [X] Yes, the DNS provider exposes a public API.
- [X] Yes, I know that the lego maintainers don't have an account in all DNS providers in the world.
- [X] Yes, I'm able to create a pull request and be able to maintain the implementation.
- [X] Yes, I'm able to test an implementation if someone creates a pull request to add the support of this DNS provider.

### How do you use lego?

Library

### Link to the DNS provider

https://www.ukfast.co.uk/dns-hosting.html

### Link to the API documentation

https://developers.ukfast.io/documentation/safedns

### Additional Notes

Hello,

I'll open a PR shortly with an implementation for this. Happy to maintain.

Thanks

**Comment by ldez** [comment] 2021-12-16 14:54
duplicate of #1503

**Closed by ldez** 2021-12-16 14:54 UTC
Labels: enhancement, new-provider
