### ISSUE TITLE
Support hook arguments

### ISSUE THREAD

**Issue by webcompas** [go-acme/lego#2184] opened 2024-05-13 15:23 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

At the moment lego doesn't support hook commands with arguments. This can lead to a huge number of scripts (or other workarounds) despite they just differ by one little thing (for example a user or application id).
If one could simply provide such information as an argument to the hook command this would make it much easier and reduce management efforts.

I would therefore very much welcome the support of arguments.

**Comment by webcompas** [comment] 2024-05-14 08:23
> Note: quotes inside the hook command are not supported.
> Do you have a concrete example?
Thanks for this hint. I really tried to use a quoted string as argument. So the minimum solution would be to improve the documentation accordingly. Currently it doesn't mention arguments at all and even worse there's no warning about the unsupported quotes (see also #1468).

In addition there may be situations where a quoted string is needed (e.g. because of spaces or other special characters) or at least useful. So the better solution would be to support quotes and also improve the documentation accordingly.

**Comment by ldez** [comment] 2024-05-14 09:29
I explained the situation here: https://github.com/go-acme/lego/issues/2168#issuecomment-2087707750

I agree that the documentation should be improved, so I flag your issue as a duplicate of #1468

**Closed by ldez** 2024-05-14 09:29 UTC
Labels: question, area/cli
