### ISSUE TITLE
"create or update" functionality

### ISSUE THREAD

**Issue by udf2457** [go-acme/lego#1463] opened 2021-08-09 14:40 UTC
### Welcome

- [X] Yes, I've searched similar issues on GitHub and didn't find any.

### How do you use lego?

Binary

### Detailed Description

Looking through the supported binary args, I can't see a flag that would enable this.

To use database terminology, it would be nice to have _"create or update"_ style functionality.

In pseudo-code:

```
if exists($domain) {
 renew
} else {
 run
}
```

Yes, I know this can be done in a `bash` wrapper to `lego`, but it would be nice to have the intelligence embedded into the binary functionality.

**Comment by ldez** [comment] 2021-08-09 14:43
Duplicate of #216 #290

**Closed by ldez** 2021-08-09 14:43 UTC
Labels: duplicate
